import type { BlogPost } from '../data';

export const commonPosts: BlogPost[] = [
  {
    id: 'react-19-transitions',
    package: 'common',
    title: 'React 19의 useTransition으로 다듬은 페이지 전환',
    excerpt:
      '레이아웃 점프와 깜빡임을 없애기 위해 라우팅 단위에 useTransition을 적용하면서 배운 것들을 정리합니다.',
    category: 'Frontend',
    authorId: 'hyeonsu',
    publishedAt: '2025-04-12',
    readingMinutes: 8,
    cover: 'linear-gradient(135deg,#4C6EF5 0%,#15AABF 100%)',
    tags: ['React', 'Performance', 'Animation'],
    body: [
      { type: 'p', text: '페이지 전환은 작은 디테일처럼 보이지만, 실제로는 사용자가 가장 자주 마주치는 인터랙션입니다. 클릭과 화면 사이의 60~120ms를 어떻게 다루느냐에 따라 제품의 인상은 완전히 달라집니다.' },
      { type: 'h2', text: '문제: 라우팅이 끝난 뒤에야 데이터가 도착한다' },
      { type: 'p', text: '기존 구조에서는 링크를 클릭하면 즉시 새 화면이 마운트되었고, 그 안에서 데이터를 fetch했습니다. 결과적으로 "빈 화면이 잠깐 보였다가 콘텐츠가 채워지는" 전형적인 깜빡임이 발생했습니다.' },
      { type: 'h2', text: '해결: 전환을 "보류"하는 useTransition' },
      { type: 'p', text: 'React 19의 useTransition은 상태 업데이트의 우선순위를 낮춰, 데이터가 준비될 때까지 이전 화면을 유지할 수 있게 해줍니다. 이를 라우터의 navigate 호출과 묶으면, 사용자에게는 마치 "다음 화면이 자연스럽게 페이드되어 들어오는" 것처럼 보입니다.' },
      { type: 'list', items: [
        '클릭 → isPending = true (이전 화면 유지)',
        '데이터 로딩 → 기존 화면을 살짝 dim 처리',
        '준비 완료 → 새 화면으로 부드럽게 교체',
      ]},
      { type: 'h2', text: '결과' },
      { type: 'p', text: 'TTI 체감 시간이 약 35% 줄었고, "어디로 이동했는지 모르겠다"는 사용자 리포트가 사라졌습니다. 코드는 더 단순해졌고, Suspense와도 자연스럽게 결합됩니다.' },
      { type: 'quote', text: '좋은 전환은 사용자가 의식하지 못하는 전환입니다.' },
    ],
  },
  {
    id: 'design-tokens-v2',
    package: 'common',
    title: '디자인 토큰을 다시 설계한 이야기',
    excerpt:
      '12개의 버튼 스타일이 공존하던 카오스에서 단일 소스(Single Source of Truth) 기반의 토큰 시스템으로 옮긴 과정.',
    category: 'Design',
    authorId: 'member-b',
    publishedAt: '2025-03-28',
    readingMinutes: 10,
    cover: 'linear-gradient(135deg,#F59E0B 0%,#EF4444 100%)',
    tags: ['Design System', 'Tokens', 'Figma'],
    body: [
      { type: 'p', text: '디자인 시스템은 "예쁜 컴포넌트 라이브러리"가 아니라, 결정의 비용을 낮추는 도구입니다. 토큰을 다시 설계하면서 이 사실을 다시 확인했습니다.' },
      { type: 'h2', text: '왜 다시 설계했나' },
      { type: 'p', text: '1년간 누적된 변형들을 헤아려보니 버튼 스타일만 12개, 카드 컴포넌트는 6개의 다른 그림자 값을 갖고 있었습니다. 새 화면을 만들 때마다 "어떤 스타일이 정답인가?"라는 질문이 반복되었고, 이건 명백히 시스템의 실패였습니다.' },
      { type: 'h2', text: '3-Tier 토큰 구조' },
      { type: 'list', items: [
        'Primitive: #4C6EF5, 16px 같은 원시 값',
        'Semantic: color.primary, spacing.md 같은 의미 기반 별칭',
        'Component: button.primary.background 같은 컴포넌트 전용 토큰',
      ]},
      { type: 'p', text: '이 구조 덕분에 다크 모드를 추가할 때 Primitive와 Component는 손대지 않고 Semantic 매핑만 교체할 수 있었습니다.' },
      { type: 'h2', text: '결과' },
      { type: 'p', text: 'Figma의 변수와 코드의 토큰이 같은 이름으로 동기화되어, 디자인 핸드오프 시간이 60% 줄었습니다. 더 중요한 것은, "어떤 색을 쓸까?"라는 질문이 사라졌다는 점입니다.' },
    ],
  },
  {
    id: 'okr-as-conversation',
    package: 'common',
    title: 'OKR을 "체크리스트"가 아닌 "대화"로 만드는 법',
    excerpt:
      '분기마다 OKR을 세우지만 실행과 따로 노는 팀이 많습니다. OKR을 살아있는 문서로 만들기 위해 우리가 시도한 것들.',
    category: 'Product',
    authorId: 'member-c',
    publishedAt: '2025-03-15',
    readingMinutes: 7,
    cover: 'linear-gradient(135deg,#8B5CF6 0%,#EC4899 100%)',
    tags: ['Strategy', 'OKR', 'Process'],
    body: [
      { type: 'p', text: 'OKR은 적는 게 어려운 게 아니라, 살아있게 만드는 게 어렵습니다. 분기 시작에 정성껏 적어두고 분기말에 다시 꺼내보는 문서가 되어선 안 됩니다.' },
      { type: 'h2', text: 'OKR이 죽는 가장 흔한 패턴' },
      { type: 'list', items: [
        '목표가 너무 많아 우선순위가 사라진다',
        'Key Result가 결과가 아닌 활동(activity)이다',
        '주간 회의에서 OKR을 언급하지 않는다',
      ]},
      { type: 'h2', text: '주간 OKR 리뷰: 15분이면 충분합니다' },
      { type: 'p', text: '매주 월요일, 15분만 OKR 진척도를 함께 봅니다. 형식은 단 세 줄: "이번 주 무엇을 했는가 / 무엇이 막혔는가 / 다음 주 어디에 베팅할 것인가". 길어지는 순간 죽습니다.' },
      { type: 'quote', text: 'OKR은 적는 도구가 아니라 대화의 매개체입니다.' },
      { type: 'h2', text: '결과' },
      { type: 'p', text: '한 분기 동안 시도한 결과, 스프린트 완료율이 65%에서 90%로 올랐습니다. 무엇을 하지 않을지 결정하는 데 더 많은 시간을 쓰게 되었습니다.' },
    ],
  },
  {
    id: 'animation-budget',
    package: 'common',
    title: '애니메이션에도 예산이 있다',
    excerpt:
      'Framer Motion을 마음껏 쓰다 보면 페이지가 무거워집니다. 60fps를 지키면서 인상적인 모션을 유지하는 우리의 규칙.',
    category: 'Frontend',
    authorId: 'hyeonsu',
    publishedAt: '2025-02-28',
    readingMinutes: 6,
    cover: 'linear-gradient(135deg,#10B981 0%,#06B6D4 100%)',
    tags: ['Performance', 'Framer Motion', 'UX'],
    body: [
      { type: 'p', text: '모션은 강력한 표현 도구지만, 동시에 가장 비싼 표현 도구입니다. 모든 요소가 동시에 움직이는 페이지는 "고급스럽다"가 아니라 "느리다"는 인상을 남깁니다.' },
      { type: 'h2', text: '우리의 3가지 규칙' },
      { type: 'list', items: [
        '한 화면에서 동시에 움직이는 "주요" 모션은 최대 3개',
        'transform과 opacity 외 속성은 가능하면 애니메이트하지 않는다',
        '300ms를 넘기지 않는다 — 사용자는 기다리고 있다',
      ]},
      { type: 'h2', text: '레이아웃 애니메이션의 함정' },
      { type: 'p', text: 'layout 속성은 매력적이지만 비쌉니다. 사용 전에 "정말 이 요소가 위치를 바꿔야 하는가?"를 물어보세요. 보통은 transform으로도 충분합니다.' },
      { type: 'p', text: '저희는 layout 애니메이션을 "주인공" 요소(아바타, 카드 전환 등)에만 쓰고, 나머지는 transform-only로 통일했습니다. 결과적으로 모바일에서도 일관되게 60fps가 나옵니다.' },
    ],
  },
  {
    id: 'small-team-rituals',
    package: 'common',
    title: '3인 팀이 지키는 작은 의식들',
    excerpt:
      '문서 없는 팀은 빠르지만 사라집니다. 3인 팀이 의사결정을 잃지 않기 위해 만든 4가지 의식.',
    category: 'Culture',
    authorId: 'member-c',
    publishedAt: '2025-02-10',
    readingMinutes: 5,
    cover: 'linear-gradient(135deg,#F472B6 0%,#A78BFA 100%)',
    tags: ['Team', 'Process', 'Culture'],
    body: [
      { type: 'p', text: '작은 팀의 강점은 속도지만, 약점도 속도입니다. 결정이 너무 빠르면 기록이 사라지고, 6개월 뒤 "왜 이렇게 만들었지?"라는 질문에 답할 수 없게 됩니다.' },
      { type: 'h2', text: '우리가 지키는 4가지' },
      { type: 'list', items: [
        '월요일 30분 — 이번 주의 단 하나의 목표를 정한다',
        '결정에는 항상 3줄 ADR을 남긴다 (배경 / 결정 / 트레이드오프)',
        '금요일 회고 — "다시 한다면 무엇을 다르게 할까?"만 묻는다',
        '분기마다 리츄얼 자체를 회고한다 — 의식이 의식 자체로 굳지 않게',
      ]},
      { type: 'p', text: '의식은 도구입니다. 도구는 일을 위해 존재하지, 일이 도구를 위해 존재하지 않습니다.' },
    ],
  },
  {
    id: 'image-pipeline',
    package: 'common',
    title: '이미지 파이프라인을 다시 만들면서 배운 것',
    excerpt:
      'CDN, WebP/AVIF, 반응형 이미지를 묶은 파이프라인을 새로 짜면서 LCP를 절반으로 줄인 과정.',
    category: 'Frontend',
    authorId: 'hyeonsu',
    publishedAt: '2025-01-22',
    readingMinutes: 9,
    cover: 'linear-gradient(135deg,#0EA5E9 0%,#6366F1 100%)',
    tags: ['Performance', 'CDN', 'Image'],
    body: [
      { type: 'p', text: '이미지는 가장 무거운 자산이면서도 가장 손이 덜 가는 자산입니다. 파이프라인을 다시 짜면서 LCP를 1.6초에서 0.8초로 줄였습니다.' },
      { type: 'h2', text: '단계별 최적화' },
      { type: 'list', items: [
        '원본은 한 곳(원본 버킷)에만 둔다',
        '요청 시 변환(on-the-fly transform)으로 width/format을 결정',
        '<picture>로 AVIF → WebP → JPEG 폴백 체인을 명시',
        'srcset과 sizes를 항상 함께 쓴다',
      ]},
      { type: 'h2', text: 'fetchpriority="high"는 마법이 아니다' },
      { type: 'p', text: 'LCP 이미지에 fetchpriority="high"를 붙이는 것은 효과적이지만, 동시에 prefetch link를 남용하면 의미가 사라집니다. 브라우저의 우선순위 큐를 이해하지 않고 사용하면 오히려 느려질 수 있습니다.' },
      { type: 'quote', text: '성능 최적화는 도구의 문제가 아니라 우선순위의 문제입니다.' },
    ],
  },
];
